version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "goodreds"
    target-branch: "main"
    versioning-strategy: "auto"
